# Generated by Django 4.2.5 on 2023-09-13 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0002_passwords_duration_passwords_duration_from_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwords',
            name='password',
        ),
        migrations.AddField(
            model_name='passwords',
            name='hashed_password',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
