# Generated by Django 4.2.5 on 2023-09-13 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0004_organisation_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='organisation.base')),
                ('number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
            bases=('organisation.base',),
        ),
    ]
