# Generated by Django 4.2.5 on 2023-09-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0008_remove_members_user_members_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwords',
            name='raw_password',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='passwords',
            name='hashed_password',
            field=models.TextField(default=''),
        ),
    ]
