# Generated by Django 4.2.5 on 2023-09-13 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0009_passwords_raw_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwords',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
