# Generated by Django 4.2.5 on 2023-09-13 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organisation', '0010_passwords_expired'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedPasswords',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='organisation.base')),
                ('view', models.BooleanField(default=True)),
                ('edit', models.BooleanField(default=True)),
                ('password', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation.passwords')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_by', to=settings.AUTH_USER_MODEL)),
                ('shared_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_to', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('organisation.base',),
        ),
    ]
